### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ryanfobel** [mtu-most/linear-actuator#10]
Hi, I am trying to figure out the licensing of the Open Source Syringe Pump design. Is it referenced anywhere? I didn't see it on the [webpage](http://www.appropedia.org/Open-source_syringe_pump) or any mention of it in the [paper](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0107216).

**Comment by wijnen** [comment]
Hi!

Sorry for the extremely late reply. The license is mentioned in the source files. For the hardware, it's CC-BY-SA, for the code it's the GNU Affero General Public License, version 3 or later.

Thanks,
Bas
