### ISSUE TITLE
End mount hole issue when using M8 lead screw

### ISSUE THREAD

**Issue by pdxalz** [mtu-most/linear-actuator#6]
I tried modifying the actuator to use an M8 leadscrew and lead nut instead of an M5.  And also increased cc_guides from 50 to 60.  Everything worked great except for the end mount holes did not move to the expected location.  The following modification to module end_mount_holes() seems to fix the problem:
was:
   translate([i * (cc_guides - idler[0] - d_lead_nut) / 2, offset_guides + j * w_ends / 2, 0])
changed to:
   translate([i * (cc_guides - l_ends/2 + d_lead_nut/2 + 1) / 2, offset_guides + j * w_ends / 2, 0])

**Comment by wijnen** [comment]
Thanks for finding that, and sorry for the very late reply.  I've fixed it in a slightly different way, by putting the hole in the center of the available space (between the idler bearing and the guide rod).
