### ISSUE TITLE
Pump server not sending signal to stepper

### ISSUE THREAD

**Issue by JeroenVanStappen** [mtu-most/linear-actuator#8]
Dear Bas,

I have a similar problem as Nick had (on one of the closed topics). I am not sure whether you would get a notification on an already closed topic, so I thought to reopen it again here.

Just like Nick I was using chrome as well, but on firefox I have similar issues. I am able to connect to the server, but on the webpage, the server also has "-" instead of numbers. I have looked up the web console on firefox and it gives following error:
"Rpc is not defined".
Also, this is one of the errors which I get on the Terminal (rpc.js not found).

Do you happen to know how to solve this.

Thanks in advance... I would be thrilled if I get the stepper motor to work.

Best regards,
Jeroen.

**Comment by wijnen** [comment]
Hi Jeroen,

While I recommend using 3-D printer controller electronics, the system should
still work.  I've updated the readme to explain the solution: you need to place
rpc.js (from python-websocketd, which you need to run the program) in the html
directory.

Let me know if that works.

Thanks,
Bas

**Comment by JeroenVanStappen** [comment]
![image](https://cloud.githubusercontent.com/assets/22395132/18787639/f2293376-81a3-11e6-889c-7c0eaf670589.png)
The server is now working correctly, and the stepper motor can be controlled through the server. I guess it is now a matter of adjusting the speed and the calibration in the pump-server command to use it at different rotation speeds. 

I am using exactly the same material as in the paper (pololu a4988 and nema 17). If you have any more tips and tricks you want to share feel free. I know I should control the current according to the needs of the stepper driver and the stepper motor  (current limit = 0.7 A(?))

Thanks already for the help with the rpc.js!
Jeroen.

**Comment by wijnen** [comment]
Hi,

Good to hear that it's working! While this setup will work for simple setups, you need a 3-D printer controller (such as Melzi or RAMPS) with software like https://github.com/mtu-most/franklin if you want to integrate the device in a setup with more sensors and/or actuators.
